language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      before_install:
        - CC=clang
        - CXX=clang++
      script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON .
        - cmake --build . --config Debug --parallel 3
    - name: "GCC Build"
      os: linux
      dist: jammy
      before_install:
        - CC=gcc-12
        - CXX=g++-12
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
    - name: "Clang Build"
      os: linux
      dist: jammy
      before_install:
        - CC=clang
        - CXX=clang++
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3

notifications:
  slack:
    secure: Fx5AGddmmeZqZBUbRdI2/zLaiWy7H+afXEWLYSEnu8+bf6sHCOTPvDsHbgPRZikAdSCa0GaxDzqVeFcOFYgX0+XPQgpY4Q2mBwrNViajxArvJXghA/4DfAAUx7knr22RbZjUsEnp2wEGU6Rp9UHo3Y+IOwXR/2v6BnQ1ntMzS1Np1X4HegHXxArrfmbx6JU+43CXajNJGcx9Bhdwnp6puCRQ+gGUz4+tSwy/0UTX4APTGKVqxuhOqRlpVkbCh1g4l6wDJ5gBP0AXM3d2BTmQYdgL6/BwqJG4REjSp6GSaoEOa22cnPtbmXnWY7/npb6uVRVo/WFvJJt6SPGOb7QJn03j/bEK1HCCIdJZR7MwxpAt7vAkihBkkb65izrKXAF05Y5dgZvJsRUCQNr3aDarPPJzU0hLV2g1o1QinuJayUtbXv3/YiP1aqM/zKe4v+J17El6X+2z+Pwvs53brOMpTIfPL/+vCNHreTKHYD90SfU44R/ObwhqS0F+pmbLwarcnwoA0ADBuorGg2HMBEU+GrTxTQiNj0p2SO+2FTFsp4AJ4LhEDsjlrvAQ2TFH3oDIpoR+IN1Pcoi4oJQ7WvFonNVj0Ndw5uJDzPMqMPy3DKNNGtUWaGy+kTHN12kWaid7HTqUDS6hye9Lq4msGwQXdmRyNjB6BENdX2Pt8L0LtEU=
    on_success: never
