language: c++

cache:
  ccache: true
  pip: true

addons:
  apt:
    packages:
      - clang
      - clang-format
      - llvm
      - lcov
      - ruby
      - gcc-12
      - g++-12
    update: true

jobs:
  include:
    - os: linux
      dist: jammy
      env:
        - RUN_TYPE=static-analysis
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      dist: jammy
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=gcc-12 && CXX=g++-12"
    - os: linux
      dist: jammy
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - tools/ci/install.sh

script:
  - tools/ci/build.sh && tools/ci/test.sh

after_success:
  - tools/ci/after_success.sh

notifications:
  slack:
    secure: MFLk4zagqALk1csb6UWXIArdkP1kimj5GTKrJl520V/e4ZhE823WfgeQHY+KMW5YpvjSGnha96xJGSudDvAi5HC6IywmRpRmiBCgId/LJp5M4iA98etZQzmrr8uIR2bFdDoLqy11te7uAZrJjVF7qo18bj5IzWT/AQHVX885eodlfkAoWKUabDIWM7PtgmGiPfAwJC8a5j16rXVlx5g95b7GwNQHhEllXg1L/hGAE0PBznuKjBh1skl7hmaeMeY/7sudpjufak6rXm7lvA3LowMWuB4v2PCFJtEr6YfILGOkTxf0se/GjR0VM0BVBdPtfKp69CRyfVhS9nn7oa1HdgO/kjY0wdYquXuTughEymHTs2v/qokXlRWOveKfRkZ2hsmRf3J6KMHXW3V0NeXNuciWXGl1JACoiroFCuh7e7iqp83Q137mbmPMNIh0fcm0qaMD7SO2qK+jvMlB7T5/C7Z6G9SjwuRVzHiXNEiEsZnpNkBaTzoAQT/rw0d+MI3LcTInTyotwzZupSNPaJuza2adxcuqV3L8QVnUtfcL6zprJ6bavzt+pM2x+WJlaT8c47FVu6on5AlyanpMSBe/p01JjZ/g7MVTiG/Wl1GJsh29IDHV4HJ6yKHI+gccmhInvNWBrkffvewbWc8GJkJLD1MCKYRaNua6vErDMdW+Fe8=
    on_success: never
